import { ANALYSIS_VERSION } from "./constants";
import { ScanResult } from "./types";

export const sampleResult: ScanResult = {
  domain: "example.com",
  analysisVersion: ANALYSIS_VERSION,
  generatedAt: new Date().toISOString(),
  findings: [
    {
      id: "DMARC_MISSING",
      category: "email_security",
      severity: "high",
      title: "DMARC policy is missing",
      summary: "No DMARC record was found for the domain.",
      business_impact: "Invoice fraud and brand impersonation risk increases without DMARC enforcement.",
      evidence: "No TXT record found for _dmarc.example.com",
      recommendation: ["Publish DMARC with p=quarantine or p=reject", "Align SPF and DKIM before enforcing"],
      weight: 25,
      priority: "P0",
    },
    {
      id: "HTTPS_NOT_ENFORCED",
      category: "hygiene",
      severity: "high",
      title: "HTTP is not redirected to HTTPS",
      summary: "Requests over HTTP are not forced to HTTPS for the same host.",
      business_impact: "Users may stay on insecure HTTP, enabling interception or tampering.",
      evidence: "GET http://example.com -> 200 without redirect",
      recommendation: ["Add a 301 redirect from HTTP to HTTPS", "Enable HSTS preload after testing redirects"],
      weight: 15,
      priority: "P0",
    },
    {
      id: "CSP_MISSING",
      category: "web_security",
      severity: "medium",
      title: "Content Security Policy is missing",
      summary: "No CSP header was found on the homepage response.",
      business_impact: "Increases exposure to XSS and data exfiltration in the browser.",
      evidence: "No Content-Security-Policy header detected.",
      recommendation: [
        "Define a restrictive CSP for scripts/styles/connect sources",
        "Roll out with report-only first, then enforce",
      ],
      weight: 8,
      priority: "P1",
    },
    {
      id: "SSL_EXPIRING_SOON",
      category: "transport_security",
      severity: "medium",
      title: "TLS certificate expires soon",
      summary: "The certificate validity ends within 14 days.",
      business_impact: "Risk of service disruption and user trust loss if renewal is missed.",
      evidence: "Certificate expires in 9 days",
      recommendation: ["Renew the TLS certificate", "Automate certificate renewal (e.g., ACME)"],
      weight: 10,
      priority: "P1",
    },
    {
      id: "HSTS_MISSING",
      category: "transport_security",
      severity: "medium",
      title: "HSTS header is missing",
      summary: "Strict-Transport-Security is not set, so browsers may downgrade to HTTP.",
      business_impact: "Opens opportunity for SSL stripping and downgrade attacks.",
      evidence: "No Strict-Transport-Security header detected.",
      recommendation: [
        "Add HSTS with long max-age and includeSubDomains",
        "Consider preload after validating redirects",
      ],
      weight: 10,
      priority: "P1",
    },
    {
      id: "XFO_MISSING",
      category: "web_security",
      severity: "low",
      title: "X-Frame-Options is missing",
      summary: "The response does not prevent clickjacking via iframes.",
      business_impact: "Attackers could frame your site to trick users into unintended actions.",
      evidence: "No X-Frame-Options header detected.",
      recommendation: ["Set X-Frame-Options: DENY or SAMEORIGIN"],
      weight: 5,
      priority: "P2",
    },
  ],
  score: {
    overall: 72,
    label: "Moderate",
    categories: {
      email_security: 60,
      transport_security: 75,
      web_security: 70,
      hygiene: 65,
    },
  },
  topFindings: [
    {
      id: "DMARC_MISSING",
      category: "email_security",
      severity: "high",
      title: "DMARC policy is missing",
      summary: "No DMARC record was found for the domain.",
      business_impact: "Invoice fraud and brand impersonation risk increases without DMARC enforcement.",
      evidence: "No TXT record found for _dmarc.example.com",
      recommendation: ["Publish DMARC with p=quarantine or p=reject", "Align SPF and DKIM before enforcing"],
      weight: 25,
      priority: "P0",
    },
    {
      id: "HTTPS_NOT_ENFORCED",
      category: "hygiene",
      severity: "high",
      title: "HTTP is not redirected to HTTPS",
      summary: "Requests over HTTP are not forced to HTTPS for the same host.",
      business_impact: "Users may stay on insecure HTTP, enabling interception or tampering.",
      evidence: "GET http://example.com -> 200 without redirect",
      recommendation: ["Add a 301 redirect from HTTP to HTTPS", "Enable HSTS preload after testing redirects"],
      weight: 15,
      priority: "P0",
    },
    {
      id: "CSP_MISSING",
      category: "web_security",
      severity: "medium",
      title: "Content Security Policy is missing",
      summary: "No CSP header was found on the homepage response.",
      business_impact: "Increases exposure to XSS and data exfiltration in the browser.",
      evidence: "No Content-Security-Policy header detected.",
      recommendation: [
        "Define a restrictive CSP for scripts/styles/connect sources",
        "Roll out with report-only first, then enforce",
      ],
      weight: 8,
      priority: "P1",
    },
  ],
};
